// components/Layout.tsx
import Head from "next/head";
import React, { ReactNode, useEffect } from "react";
import type { Metadata } from "next";
import Header from "./Header";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Taiwo Ademola</title>
        <meta
          name="description"
          content="I am a Product & Graphic Designer with a keen eye for user-centered, intuitive, and visually stimulating designs. I propel startups and large corporations towards success by designing the perfect digital solutions."
          key="desc"
        />
        <meta property="og:title" content="Taiwo Ademola" />
        <meta
          property="og:description"
          content="I am a Product & Graphic Designer with a keen eye for user-centered, intuitive, and visually stimulating designs. I propel startups and large corporations towards success by designing the perfect digital solutions."
        />
        <meta
          property="og:image"
          content="https://example.com/images/cool-page.jpg"
        />
      </Head>

      <div className="flex bg-[#190634]">
        <div className="flex-1 bg-[#190634] flex flex-col max-w-screen-xl mx-auto px-4">
          <Header />
          <main className="flex-1 p-4 md:p-6">{children}</main>
          <Footer />
        </div>
      </div>
    </div>
  );
};

export default Layout;
